# SITE CONFIGURATION
title: Matteo & Lorenza # your site title
author: Lori and Matte # You :P
description: > # Meta description of Homepage
  Wedding website for Lori and Matte
tagline: >
  19-06-2021

baseurl: "/wedding" # the subpath of your site, e.g. /blog


# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Gift idea', link: '/honeymoon/'}
  - {name: 'Tips & recommendations', link: '/tipsandrecommendations'}
  - {name: 'Directions', link: '/directions'}
  - {name: 'Italiano', link: '/ita'} 
  - {name: 'Search', link: '/search/'}

navigation_ita: 
  - {name: 'Home', link: '/ita/'}
  - {name: 'Idee regalo', link: '/ita/lunadimiele/'}
  - {name: 'Consigli', link: '/ita/consigli'}
  - {name: 'Come arrivare', link: '/ita/comearrivare'}
  - {name: 'Covid', link: '/ita/linee-guida/covid'}
  - {name: 'English', link: '/'} 
  - {name: 'Cerca', link: '/search/'}

hero_img: posts/matteoLori2.jpg 

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge 
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
